name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Configurar Android
        uses: android-actions/setup-android@v3

      - name: Baixar Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-8.7-bin.zip
          unzip -q gradle-8.7-bin.zip

      - name: Gerar APK
        run: |
          ./gradle-8.7/bin/gradle assembleDebug

      - name: Salvar APK
        uses: actions/upload-artifact@v4
        with:
          name: Armario-do-Everton-APK
          path: app/build/outputs/apk/debug/app-debug.apk
